### ISSUE TITLE
Use of Powershell can be problematic for containers

### ISSUE THREAD

**Issue by cfernald** [microsoft/mu_devops#8]
Requiring PowerShell for contains can increase their size by ~0.25 Gb for fairly limited use. It may be best to use common environment scripting rather than relying on PowerShell.

**Comment by spbrogan** [comment]
I agree with this.  shell/cmd might also be a problem.  We have seen self-hosted agents that don't have access to bash.  

We could leverage python as you can do inline scripting and since everything else we do is python it might be reasonable.
