### ISSUE TITLE
[Bug] Code coverage results missing in pipeline UI

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_devops#84]
Some code coverage results are not reported in the Azure pipeline UI.

For example this build runs MacAddressEmulationDxe tests, but they do not appear in the coverage.xml 

- https://dev.azure.com/projectmu/mu/_build/results?buildId=34335&view=ms.vss-test-web.build-test-results-tab
Pipelines

There's also been changes to code coverage reporting and result file merge capabilities added to edk2 recently. See:

https://github.com/tianocore/edk2/pull/3349

This task tracks reviewing and updating code coverage for Project Mu repos.

**Comment by makubacki** [comment]
@cfernald I recall the dotnet fix in the container image being related to this. Is it resolved now that #99 is merged? Or are additional changes needed?

**Comment by cfernald** [comment]
@makubacki I think it depends slightly the original intent of this issue. This resolve the issue of the code coverage data no longer being collected, but there is still issues with the HTML UI not showing all of the code, so I think some more work is required in the HTML generation.

**Comment by makubacki** [comment]
> there is still issues with the HTML UI not showing all of the code, so I think some more work is required in the HTML generation.

I agree that this issue should track resolving that as well.

**Comment by cfernald** [comment]
Resolved with https://github.com/microsoft/mu_devops/pull/138
